### PR TITLE
hu locale update & icon update

### PR DESCRIPTION
**Pull request by ovari**

### CODE REVIEW

**Comment by dugite-code** [comment]
@ovari Could you split the Icon change off to a separate pull request? I would rather look into that separately

**Comment by ovari** [comment]
Don't know how to do separate pull requests. We can delete the icons. Please accept the hu locale and then we can redo the icons.

**Comment by dugite-code** [comment]
Thanks for your contribution

**Comment by ovari** [comment]
You are welcome

**Pull request merged**
